### ISSUE TITLE
About pytest

### ISSUE THREAD

**Issue by avenger123456** [centreborelli/sat-bundleadjust#7]
Hello, when I do pytest I found this error, do you know how to resolve it?
 
================================================================================== short test summary info ==================================================================================FAILED tests/test_ba.py::test_ba - pyproj.exceptions.CRSError: Invalid projection: +proj=utm +zone=18P +type=crs: (Internal Proj Error: proj_create: Error 1027 (Invalid value for an argu...

**Comment by tehret** [comment]
Can you try with version 3.0.1 of pyproj (pip install pyproj==3.0.1) ?
